# Here are many constants defined, to prevent spelling mistakes

module.exports =
  textChange:         "textChange"
  insertion:          "insertion"
  deletion:           "deletion"
  replacement:        "replacement"
  getText:            "getText"
  sendText:           "sendText"
  addCursor:          "addCursor"
  updateCursor:       "updateCursor"
  removeCursor:       "removeCursor"
  selectionChanged:   "selectionChanged"
  clientConnected:    "newClient"
  clientDisconnected: "clientDisconnected"
  initialize:         "initialize"
  initialized:        "initialized"
  clear:              "clear"
  connecting:         "connecting"
  acknowledge:        "acknowledge"
  newUser:            "newUser"
  userLeft:           "userLeft"
  connected:          "connected"